server:
  port: 10001
sidecar:
  port: 8000

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
#zuul可以设置哪些服务不对提供
zuul:
  host:
    max-total-connections: 200
    max-per-route-connections: 20
  routes:
    users: /myusers/*
#  prefix: /api
#  strip-prefix: false
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000
  
eureka:
  instance:
    hostname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://microNote:8761/eureka/