spring:
  application:
    name: notifyServer

server:
  port: 9020
  context-path: /microNote
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
        
weeklyReport:
  noitfy:
    uris:
      serverUri: http://localhost:9001/
      Report: /sseresrse
    notifyThreadNumber: 4
    cron:
      onWeeklyReportSubmit: 0/60 * 9-23 * * *
      notifyAuditingUser: 0/30 * * * * *
      notifyUserSubimtWeeklyReportOnEveryWeekend: 0 0 0/1 * * FRI
kara:
  accessToken: bearer fff412aa166143b285a414e3b805e1e6
  karaService: http://10.19.15.36:16010/
  incomingUri: /api/webapi/incoming/services/reception
  
