spring:
  application:
    name: weeklyreport
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    database: mysql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.5.5.60:3306/micro_note?characterEncoding=utf8&useSSL=false
#    url: jdbc:mysql://localhost:3306/micro_note?characterEncoding=utf8&useSSL=false
    username: mnote
    password: 12345
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    data: data-mysql.sql

server:
  port: 9001
  context-path: /microNote
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://microNote:8761/eureka/
  #add by zhaojl 2017-1-12 solve Eureka EMERGENCY Warnning
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

logging:
  level:
    org:
      hibernate:
        SQL: debug
weeklyReport:
  notify:
    information: 您有%count%周报待查看请访问链接 http://localhost:8020/queryWeeklyReportTo/%userId%/%week%
kara:
  url:
    getStaffByAccountId: http://10.19.15.28:8000/api/sdm/getStaffByAccountId/{accountId}
    getStaffByStaffId: http://10.19.15.28:8000/api/sdm/getStaffByStaffId/{staffId}
