spring:
  application:
    name: notifyServer
  rabbitmq:
    host: 10.5.5.58
    port: 5673
    username: mnote
    password: 12345
    virtualHost: mnote

server:
  port: 9020
  context-path: /microNote
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
        
weeklyReport:
  noitfy:
    uris:
      serverUri: http://localhost:9001/
      Report: /sseresrse
    notifyThreadNumber: 4
    cron:
      onWeeklyReportSubmit: 0/60 * 9-23 * * *
      notifyAuditingUser: 0/30 * * * * *
      notifyUserSubimtWeeklyReportOnEveryWeekend: 0 0/60 9-18 * * FRI
kara:
  accessToken: bearer 9f72b0d71fd443d28d5cae1f754d23fd
  karaService: http://10.19.15.36:16010/
  incomingUri: /api/v1.0.0/webapi/incoming/services/reception
